services:
  - type: web
    name: loan-flask-api
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: "python run.py"
    runtime: python
    branch: main
    autoDeploy: true
